<a href="https://colab.research.google.com/github/Rahmat-ML/math-for-ml/blob/main/session-8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[6, 4, 24], [1, -9, 8]])
a

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [4]:
a.shape

(2, 3)

In [9]:
a[0]

array([ 6,  4, 24])

In [11]:
a[:,1]

array([ 4, -9])

In [14]:
print(a[0, 0])

6


In [15]:
b = np.array([[3, 5, 2],
              [1, 6, 9],
              [29, 10, 21]])

In [17]:
print(b[1:3, 1:2])

[[ 6]
 [10]]


In [19]:
print(b.sum())

86


In [21]:
print(b)
print('sum of rows:', b.sum(axis=1))
print('sum of columns:', b.sum(axis=0))

[[ 3  5  2]
 [ 1  6  9]
 [29 10 21]]
sum of rows: [10 16 60]
sum of columns: [33 21 32]


In [24]:
a = np.array([[4, 5], [2, 0]])
b = np.array([[4, 6], [7, 1]])

print('a\n', a)
print('b\n', b)

a
 [[4 5]
 [2 0]]
b
 [[4 6]
 [7 1]]


In [25]:
print(a + b)

[[ 8 11]
 [ 9  1]]


In [26]:
print(a * b)

[[16 30]
 [14  0]]


In [27]:
print(np.dot(a, b))

[[51 29]
 [ 8 12]]


In [31]:
a = np.array([[32, 12, 43], [51, 41, 91]])
print(a)

[[32 12 43]
 [51 41 91]]


In [32]:
print(a.T)

[[32 51]
 [12 41]
 [43 91]]


In [33]:
print(a.T.T)

[[32 12 43]
 [51 41 91]]


In [36]:
a = np.array([[1, 4, 5], [4, 2, 6], [5, 6, 3]])
print(a)

[[1 4 5]
 [4 2 6]
 [5 6 3]]


In [37]:
print(a.T)

[[1 4 5]
 [4 2 6]
 [5 6 3]]


In [38]:
print(a == a.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [40]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print('trace:', np.trace(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
trace: 15


In [42]:
a = np.array([[8, 3],
              [4, 2]])
print('a:\n', a)
a_det = np.linalg.det(a)
print(a_det)

a:
 [[8 3]
 [4 2]]
3.999999999999999


In [44]:
print(np.round(a_det))

4.0


In [45]:
b = np.array([[1, 2, 3],
              [3, 2, 1],
              [0, 0, 1]])
print(b)

[[1 2 3]
 [3 2 1]
 [0 0 1]]


In [46]:
print(np.linalg.det(b))

-4.000000000000001


In [47]:
print(np.linalg.det(np.array([[1, 2, 3],
                              [0, 4, 5],
                              [0, 0, 6]])))

23.999999999999993


In [48]:
print(np.linalg.inv(np.array([[4, 3], [3, 2]])))

[[-2.  3.]
 [ 3. -4.]]


In [49]:
print(np.linalg.inv(np.array([[1, 2, 3],
                              [0, 1, 4],
                              [5, 6, 0]])))

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [50]:
a = np.array([[1, 2],
              [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [51]:
print(np.linalg.norm(a))

5.477225575051661


In [52]:
print(np.sqrt(np.trace(np.dot(a.T, a))))

5.477225575051661


# now we are using SymPy

In [54]:
import sympy as sp

In [57]:
a = sp.Matrix([[-6, 3],
               [4, 5]])
# print(a)
a

Matrix([
[-6, 3],
[ 4, 5]])

In [59]:
a.row(0)

Matrix([[-6, 3]])

In [60]:
a.col(0)

Matrix([
[-6],
[ 4]])

In [62]:
a.shape

(2, 2)

In [63]:
a.inv()

Matrix([
[-5/42, 1/14],
[ 2/21,  1/7]])

In [65]:
a.det()

-42

In [67]:
a = sp.Matrix([[8, 3],
               [4, 2]])
a

Matrix([
[8, 3],
[4, 2]])

In [68]:
a.det()

4

In [69]:
a.inv()

Matrix([
[1/2, -3/4],
[ -1,    2]])

In [70]:
sp.zeros(4, 5)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [71]:
sp.eye(5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [72]:
sp.diag(1, 2, 4, 3)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 4, 0],
[0, 0, 0, 3]])