<a href="https://colab.research.google.com/github/Rahmat-ML/math-for-ml/blob/main/session-20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
A = np.array([[1, 4],
              [3, 2]])
print(A)

[[1 4]
 [3 2]]


In [8]:
l, V = np.linalg.eig(A)
print(l) # مقدار ویژه
print(V) # بردارهای ویژه

[-2.  5.]
[[-0.8        -0.70710678]
 [ 0.6        -0.70710678]]


In [9]:
print(np.around(V, decimals=2))

[[-0.8  -0.71]
 [ 0.6  -0.71]]


In [10]:
# AV = l*V

l[0] * V[:, 0]

array([ 1.6, -1.2])

In [12]:
np.dot(A, V[:, 0])

array([ 1.6, -1.2])

In [13]:
l[1] * V[:, 1]

array([-3.53553391, -3.53553391])

In [14]:
np.dot(A, V[:, 1])

array([-3.53553391, -3.53553391])

In [15]:
A = np.array([[1, 2, 3],
              [0, 3, 0],
              [0, 0, 1]])
A

array([[1, 2, 3],
       [0, 3, 0],
       [0, 0, 1]])

In [19]:
l, V = np.linalg.eig(A)
print(l)
print(np.around(V, decimals=2))

[1. 3. 1.]
[[ 1.    0.71 -1.  ]
 [ 0.    0.71  0.  ]
 [ 0.    0.    0.  ]]


# using `SymPy`

In [20]:
import sympy as sp

In [21]:
A = sp.Matrix([[1, 2, 3],
              [0, 3, 0],
              [0, 0, 1]])
A

Matrix([
[1, 2, 3],
[0, 3, 0],
[0, 0, 1]])

In [22]:
A.eigenvals()

{3: 1, 1: 2}

In [23]:
A.eigenvects()

[(1,
  2,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [0]])])]