<a href="https://colab.research.google.com/github/Rahmat-ML/math-for-ml/blob/main/session-22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[3, 1, 1],
              [-1, 3, 1]])

In [3]:
A

array([[ 3,  1,  1],
       [-1,  3,  1]])

In [4]:
A.T

array([[ 3, -1],
       [ 1,  3],
       [ 1,  1]])

In [5]:
np.dot(A, A.T)

array([[11,  1],
       [ 1, 11]])

In [6]:
np.dot(A.T, A)

array([[10,  0,  2],
       [ 0, 10,  4],
       [ 2,  4,  2]])

In [19]:
U, s, Vt = np.linalg.svd(A)

In [20]:
print('U:\n', np.round(U, decimals=2))
print('S:\n', np.round(s, decimals=2))
print('Vt:\n', np.round(Vt, decimals=2))

U:
 [[-0.71 -0.71]
 [-0.71  0.71]]
S:
 [3.46 3.16]
Vt:
 [[-0.41 -0.82 -0.41]
 [-0.89  0.45  0.  ]
 [-0.18 -0.37  0.91]]


In [24]:
# A ?= US(Vt)
S = np.zeros((2, 3))
S[:2, :2] = np.diag(s)
S

array([[3.46410162, 0.        , 0.        ],
       [0.        , 3.16227766, 0.        ]])

In [25]:
np.dot(np.dot(U, S), Vt)

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])